package net.cd.exception;

/**
 * Created by Vincent 01/12/2017
 */
public enum CdErrors {

    CD_VERSION_MISMATCH(8000),
    CD_ACCESS_IS_DENIED(8001),
    CD_INTERNAL_SERVER_ERROR(8002),
    CD_K_MEMBER_ALREADY_EXISTS(8003),
    CD_K_MEMBER_NOT_EXISTS(8004),
    CD_K_MEMBER_ALREADY_ACTIVATED(8005),
    CD_K_MEMBER_NOT_ACTIVATED(8006),
    CD_K_MEMBER_INVALID_EMAIL_ADDRESS(8007),
    CD_T_VERIFICATION_CODE_EXPIRY_OR_INVALID(8009),
    CD_K_ASSET_NOT_EXISTS(8010),
    CD_K_ASSET_RETAIN_FAILURE_FILE_EMPTY(8011),
    CD_K_ASSET_RETAIN_FAILURE_TTL_EXPIRED(8012),
    CD_K_ASSET_FETCH_FAILURE_FILE_UNAVAILABLE(8013),
    CD_K_ASSET_FETCH_FAILURE_TTL_EXPIRED(8014),
    CD_K_ASSET_FETCH_FAILURE_FILE_UNOBTAINABLE(8015),
    CD_K_ASSET_TYPE_NOT_DETERMINES(8016),
    CD_K_REGISTRANT_NOT_EXISTS(8017),
    CD_K_BILLING_NOT_EXISTS(8018),
    CD_K_BILLING_NOT_PAYABLE(8019),
    CD_T_MAIL_EXCEPTION(8020),
    CD_T_SMS_EXCEPTION_PAYLOAD_LENGTH_EXCEED_LIMIT(8021),
    CD_K_MEMBER_USERNAME_ALREADY_EXISTS(8022),
    CD_K_MEMBER_MOBILE_ALREADY_EXISTS(8023),
    CD_K_MEMBER_EMAIL_ALREADY_EXISTS(8024),
    CD_K_RESOURCE_NOT_EXISTS(8025),
    CD_K_COMMENT_NOT_EXISTS(8026),
    ;

    private Integer code;

    CdErrors(Integer code) {
        this.code = code;
    }

    public Integer getCode() {
        return code;
    }
}
